(ns crawler.data)

(def lists
  {:pixel-prophecy ["commanderstitch"
                    "philstrahl"
                    "incd021"
                    "rombus"
                    "redhermit"
                    "spacemonkey"
                    "hedgy"
                    "preda"
                    "frank-gevaerts"
                    "lilou-cormic"
                    "ladymistleaf"
                    "deathstorm"
                    "jiri-hysek"
                    "milestone-games"
                    "yngvarr"
                    "enderr42"
                    "bereg"
                    "grimmpaperman"
                    "bangkerpow"
                    "tudvari"
                    "balimaarthebassfish"
                    "kirsybuu"]

   :old-friends ["secretpocketcat"
                 "hacksawunit"
                 "aviktorov"
                 "felegz"
                 "victory"
                 "udo"
                 "bwalter"
                 "flaterectomy"
                 "deepnight"
                 "hilvon"
                 "bibilega"
                 "devharts"
                 "hexkritor"
                 "dolorosso"
                 "daria-s"
                 "phoenixking"
                 "klirik"
                 "kvinster"
                 "ultrashel"
                 "gagapete"
                 "jdah"
                 "torcado"
                 "voxel"
                 "benjamin"
                 "trasevol-dog"]
   :vas3k-ludum-dare ["yogurtthehorse"
                      "quasilyte"]})

